### ISSUE TITLE
Remove okhttp from sendanywhere jar

### ISSUE THREAD

**Issue by gfhuertac** [estmob/SendAnywhere-Android-SDK#1]
It is better to add it in the build.gradle file, since it can conflict with other libraries (like Picasso) when added directly in the jar file. Using

    compile 'com.squareup.okhttp:okhttp:2.4.0'

(or another version) solves the issue.

EDIT: The current way also obfuscate the methods from okhttp, so there are duplicated classes but with different methods, complicating things more.

**Comment by bskim45** [comment]
We moved library dependencies to gradle management system. Thanks!
