### ISSUE TITLE
Be careful.

### ISSUE THREAD

**Issue by audiorecorder** [estmob/SendAnywhere-Android-SDK#10]
Be careful.
If you earn any profits using this API, you will be required to pay 80% of your profits.
Last year, I developed a small app with this API and received an email saying that if you do not share revenue), We(sendanywhere) will stop the API. and They stop the API.
Funny people.
Stay away from this API, and Read their policy carefully before doing something.

**Comment by kyujin-sah** [comment]
I don’t think it is true what you mentioned. If you don’t mind, would you please give us your information such as your app name or email address used with Send Anywhere. Then, we will check it out what was going on.
