### ISSUE TITLE
Failure to write File due to missing permission

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#2]
This demo targets Android 23, but fails to ask for permissions at runtime to write files (WRITE_EXTERNAL_STORAGE).
Result is this:
W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
W/System.err:     at java.io.File.createNewFile(File.java:939)
W/System.err:     at com.estmob.paprika.transfer.util.FileUtils.createFile(FileUtils.java:59)
W/System.err:     at com.estmob.paprika.transfer.protocol.Transfer.recv(Transfer.java:126)
W/System.err:     at com.estmob.paprika.transfer.protocol.ActiveHttp.recv(ActiveHttp.java:135)
W/System.err:     at com.estmob.paprika.transfer.protocol.ActiveMultiHttp.transfer(ActiveMultiHttp.java:30)
W/System.err:     at com.estmob.paprika.transfer.protocol.ActiveMultiHttp.access$000(ActiveMultiHttp.java:13)
W/System.err:     at com.estmob.paprika.transfer.protocol.ActiveMultiHttp$1.run(ActiveMultiHttp.java:53)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

Solution: at activity start, ask for permissions:
Activity.onCreate:
if(Build.VERSION.SDK_INT>=23){
   int p = ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE);
         if(PackageManager.PERMISSION_GRANTED!=p){
            requestPermissions(new String[]{Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1);
         }
   }

   @Override
   public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults){
      if(permissions.length>0){
         if(grantResults[0]==PackageManager.PERMISSION_GRANTED)
            work();
      }
   }

**Comment by bskim45** [comment]
Thanks @mice777 
We updated our sample to handle runtime permission.
