### ISSUE TITLE
Duplication of state constants, and missing Javadoc

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#3]
`Task.State` and `Task.DetailedState` declare constants that are mirrors of constants already defined in `TransferTask.State, TransferTask.DetailedState, UploadTask.State, DownloadTask.State`, etc.

Why this duplication? Complexity grows for no reason.

Similar for `Task.FileInfo`, which is duplicate of `TransferTask.FileState`.

Maybe it's good to provide **Javadoc**, for now one can only study library code (thanks to Android Studio class decompiler).

**Comment by bskim45** [comment]
Those classes you've mentioned are internal classes used in the backstage.
We created helper classes(which extends `Task`) encapsulating internal classes to provide easier interface, and to deal with some security reasons.

You don't actually have to concern about internal classes.

**Comment by bskim45** [comment]
I misunderstand your suggestion.
Fixed at 4880f41bcb178045b9e0c4d15e34d7d43ae9e4f9
