### ISSUE TITLE
proguard build doesn't compile

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#4]
When enabling minification in app/build.gradle:

buildTypes {
        release {
            minifyEnabled true
      ...
   }
}

the project fails to build with lots of errors like these:
`Warning:library class android.net.http.AndroidHttpClientConnection extends or implements program class org.apache.http.HttpInetConnection`
`Warning:library class android.net.http.AndroidHttpClientConnection extends or implements program class org.apache.http.HttpConnection`
`Warning:library class com.android.internal.http.multipart.MultipartEntity extends or implements program class org.apache.http.entity.AbstractHttpEntity`

My project needs to be built with proguard enabled, and right after adding dependency on com.estmob.android:sendanywhere-core:6.6.10@aar` library, release build of my app fails with above errors.

You may need to tune proguard files, or something else.

**Comment by mice777** [comment]
Possible fix: add this to app/proguard-rules.pro

> -dontnote org.apache.http.**
> -dontnote com.squareup.okhttp.**
> -dontnote android.support.v4.**
> -dontnote com.google.android.gms.**
> -dontnote android.net.http.*
> 
> -dontwarn okio.**
> -dontwarn org.apache.http.**
>

**Comment by bskim45** [comment]
again, thanks for help @mice777!
We added Proguard rules to our sample app (https://github.com/estmob/SendAnywhere-Android-SDK/blob/master/app/proguard-rules.pro)
