### ISSUE TITLE
Key expiration time is not defined in SDK.

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#5]
The key is expiring after 10 minutes.
While this is known constant from service description, it may change in future, and apps can become broken.

Ideally the SDK should report the expiration countdown back to app in callback, so that app doesn't have to count itself and hard-code 10 minutes. Or at least there should be a method to determine after which time the key expires.

The purpose for this request is to display nice counter as is shown on your website.
For now I have to assume fixed 10 minutes and hope that it won't change.

**Comment by bskim45** [comment]
fixed at d7ff472a642ee4c7531e2f23294b13375a396109
