### ISSUE TITLE
UploadTask doesn't work correctly with content:// uri

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#6]
My app needs to upload file that is not stored in traditional File, but rather comes from other source (zip file / cloud server / etc). 

Your API at present accepts only traditional files, although it claims to work with Uri and attempts to recognize content:// uri, but only to resolve them as File or DocumentFile.
A content uri may look like this: content://com.example.app.FileContent/ABCXYZ
When passing in such Uri, your SDK crashes:
`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference`
`   at com.estmob.paprika.transfer.TransferTask$FileState.set(TransferTask.java:165)`
`   at com.estmob.paprika.transfer.TransferTask$FileState.<init>(TransferTask.java:154)`
`   at com.estmob.paprika.transfer.UploadTask.updateFileList(UploadTask.java:443)`
`   at com.estmob.paprika.transfer.TransferTask.actionTransfer(TransferTask.java:721)`
`   at com.estmob.paprika.transfer.TransferTask.actionFileServer(TransferTask.java:658)`
`   at com.estmob.paprika.transfer.TransferTask.run(TransferTask.java:571)`
`   at com.estmob.paprika.transfer.UploadTask.run(UploadTask.java:248)`
`   at java.lang.Thread.run(Thread.java:818)`

The API has to work with Android's ContentResolver to get file's size and stream. This is standard Android's way to provide "content". 
Example:
```
ContentResolver cr = getContentResolver();
try{
   AssetFileDescriptor afd = cr.openAssetFileDescriptor(uri, "r");
   if(afd!=null){
      size = afd.getLength();
      afd.close();
   }
}catch(IOException | SecurityException e){
   e.printStackTrace();
}
InputStream is = cr.openInputStream(uri);
...
```

Or better yet, redesign `UploadTask.FileInfo` to return file size, modification date, and open file's stream, instead of using Uri, and we're done. No content resolving or similar, just providing needed file's data, that's all what's necessary.
Hint:
```
class UploadTask{
...
   interface FileInfo {
      String getPathName();
      long getLength();
      long getLastModifyTime();
      InputStream openStream() throws IOException;
   }
}
```

**Comment by bskim45** [comment]
We are working on for that. I'll let you know when it's fixed. @mice777

**Comment by bskim45** [comment]
fixed on https://github.com/estmob/SendAnywhere-Android-SDK/releases/tag/v6.7.20
