### ISSUE TITLE
Library version 6.7.20 produces many compilation warnings

### ISSUE THREAD

**Issue by mice777** [estmob/SendAnywhere-Android-SDK#7]
It is desirable to produce clean build without warnings. Adding your library makes long warning message in Android Studio. This can possibly hide other important warning messages.
Please clean it.

Information:Gradle tasks [:app:assembleDebug]
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(com.estmob.paprika.transfer.a) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.

![capture](https://cloud.githubusercontent.com/assets/3145438/16995727/3f4aee5c-4eae-11e6-8e39-c7c40853fef0.PNG)

**Comment by bskim45** [comment]
Put `-keepattributes InnerClasses` or `-dontwarn com.estmob.paprika.transfer` to your proguard rules.
Bunch of rules will be provided as consumer proguard rule on the next version.

**Comment by bskim45** [comment]
This will be fixed on the next release shipping with bunch of consumer proguard rules.

**Comment by bskim45** [comment]
fixed at https://github.com/estmob/SendAnywhere-Android-SDK/releases/tag/v6.7.21
Thanks for reporting!
